image: gradle:latest

build:
  stage: build
  script: gradle classes testClasses

test:
  stage: test
  script: gradle test
  artifacts:
    when: always
    reports:
      junit: '**/build/test-results/test/**/TEST-*.xml'
