image: pikalab/ci:ubuntu-jdk14-git-gradle-graphviz

variables:
  GOPTS: "--no-daemon --console=plain"

before_script:
  - chmod +x gradlew
  - source $HOME/.sdkman/bin/sdkman-init.sh

build:
  stage: build
  script: ./gradlew assemble $GOPTS

test:
  stage: test
  script: ./gradlew check $GOPTS

