/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unibo.ds.flatproject;

public class App {
    public static String greet(String... args) {
        return String.format("Hello %s!", args[0]);
    }

    public static void main(String[] args) {
        System.out.println(greet(args));
    }
}
