/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unibo.ds.flatproject;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void testMain() {
        assertEquals("Hello Giovanni!", App.greet("Giovanni"));
        assertEquals("Hello Andrea!", App.greet("Andrea"));
        assertEquals("Hello Andrea!", App.greet("Andrea", "e", "Giovanni"));
    }
}
