image: pikalab/ci:ubuntu-jdk14-git-gradle-graphviz

before_script:
  - chmod +x gradlew
  - source $HOME/.sdkman/bin/sdkman-init.sh

variables:
  GOPTS: "--no-daemon --console=plain"

build:
  stage: build
  script: gradle classes javadoc $GOPTS

test:
  stage: test
  script: gradle check $GOPTS
